# Usa una imagen base de Python 3.7
FROM python:3.7-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia todos los archivos del proyecto en el contenedor
COPY . /app

# Instala dependencias del sistema necesarias para compilar paquetes de Python
RUN apt-get update && \
    apt-get install -y gcc g++ && \
    apt-get clean

# Instala Jupyter Notebook y las dependencias necesarias
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install jupyter

# Descarga e instala el modelo de spaCy
RUN python -m spacy download es_core_news_sm

# Expone el puerto 8888 para Jupyter Notebook y el puerto 5000 para Flask
EXPOSE 8888
EXPOSE 5001

# Comando para ejecutar Jupyter Notebook y el servidor Flask
CMD ["sh", "-c", "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root & python app.py"]
